google_analytics:
menu:
  archives: '/archives/'
  about: '/about/'
index:
  pager:
    range: 0
widgets:
  toc:
    enabled: true
  recent_reply:
    enabled: true
  category:
    enabled: true
  tag:
    enabled: true
  other:
    enabled: true
